common/urls.py
from django.conf import settings
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LoginView
from django.urls import include, path
from django.views.static import serve

from main import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', LoginView.as_view(template_name='login.html'), name='login'),
    path('captcha/', include('captcha.urls')),
    path('summernote/', include('django_summernote.urls')),

    path('', views.HomeView.as_view(), name='home'),
    path('contact/', views.ContactView.as_view(), {'slug': 'contact'}, name='contact'),
    path('agenda/', views.AgendaView.as_view(), {'slug': 'agenda'}, name='agenda'),
    path('evenement/<int:target>/', views.EventView.as_view(), name='event'),

    path('galerie/', views.GalleryListView.as_view(), name='galleries'),
    path('galerie/edit/', login_required(views.PageEditView.as_view()), kwargs={'slug': 'galerie'}),
    path('galerie/<slug:slug>/', views.GalleryDetailView.as_view(), name='gallery'),

    path('<slug:slug>/', views.PageView.as_view(), name='page'),
    path('<slug:slug>/edit/', login_required(views.PageEditView.as_view()), name='page_edit'),
]


if settings.DEBUG:
    urlpatterns += [
        path('media/<path:path>', serve, {
            'document_root': settings.MEDIA_ROOT,
        }),
    ]

main/models.py
from datetime import date

from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericForeignKey, GenericRelation
from django.db import models
from django.urls import reverse
from django.utils import dateformat

from mptt.models import MPTTModel, TreeForeignKey


class Attachment(models.Model):
    upfile = models.FileField("Fichier", upload_to='fichiers')
    title = models.CharField("Titre", max_length=250)
    uploaded = models.DateTimeField(auto_now_add=True)
    visible = models.BooleanField(default=True)
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey()

    class Meta:
        verbose_name = 'Fichier joint'
        verbose_name_plural = 'Fichiers joints'

    def __str__(self):
        return "%s (%s)" % (self.title, self.upfile)


class Page(MPTTModel):
    slug = models.SlugField()
    title = models.CharField(max_length=150)
    menu_title = models.CharField(max_length=100, blank=True,
        help_text="Titre court de la page pour les menus")
    content = models.TextField()
    parent = TreeForeignKey(
        'self', null=True, blank=True, related_name='children',
        on_delete=models.SET_NULL, db_index=True
    )
    weight = models.IntegerField("Poids", default=0)
    attachments = GenericRelation(Attachment)

    class Meta:
        ordering = ('weight',)

    class MPTTMeta:
        order_insertion_by = ['title']

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('page', kwargs={'slug': self.slug})

    def get_menu_title(self):
        return self.menu_title or self.title


class FutureManager(models.Manager):
    """Future published events."""
    def get_queryset(self):
        return super().get_queryset().filter(pub_date__lte=date.today()
            ).filter(models.Q(end_date__isnull=False, end_date__gte=date.today()) |
                     models.Q(end_date__isnull=True, start_date__gte=date.today()))


class PassedManager(models.Manager):
    """Passed published events."""
    def get_queryset(self):
        return super().get_queryset().filter(pub_date__lte=date.today()
            ).filter(models.Q(end_date__isnull=False, end_date__lt=date.today()) |
                     models.Q(end_date__isnull=True, start_date__lt=date.today()))


class Event(models.Model):
    EVENT_CHOICES = (
        ('cafe', 'Café-Conférence'),
        ('autre', 'Autre'),
    )
    DATE_FORMAT = 'l j F Y'  # mardi 3 avril 2015
    DATE_FORMAT_SHORT = 'j.n.Y'  # 4.4.2015
    TIME_FORMAT = 'H:i'  # 09:30

    pub_date = models.DateField("Date de publication",
        help_text="Si la date est dans le futur, la nouvelle ne sera publiée qu'à cette date")
    start_date = models.DateField("Date début")
    start_hour = models.TimeField("Heure début", blank=True, null=True)
    end_date = models.DateField("Date fin", blank=True, null=True)
    end_hour = models.TimeField("Heure fin", blank=True, null=True)
    title = models.CharField("Titre", max_length=255)
    description = models.TextField("Description", blank=True)
    event_type = models.CharField("Type", max_length=20, choices=EVENT_CHOICES)

    objects = models.Manager()
    published = FutureManager()
    passed = PassedManager()

    class Meta:
        verbose_name = 'Événement'

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('event', args=[self.pk])

    @property
    def is_passed(self):
        return (
            (self.end_date is not None and self.end_date < date.today()) or
            (self.end_date is None and self.start_date < date.today())
        )

    def date_long(self, hour=False):
        content = ''
        if self.end_date:
            content = "du %s" % dateformat.format(self.start_date, self.DATE_FORMAT)
            if hour and self.start_hour:
                content += " (%s)" % dateformat.time_format(self.start_hour, self.TIME_FORMAT)
            content += " au %s" % dateformat.format(self.end_date, self.DATE_FORMAT)
            if hour and self.end_hour:
                content += " (%s)" % dateformat.time_format(self.end_hour, self.TIME_FORMAT)
        else:
            content = dateformat.format(self.start_date, self.DATE_FORMAT)
            if hour and self.end_hour and self.start_hour:
                content += " (%s - %s)" % (
                    dateformat.time_format(self.start_hour, self.TIME_FORMAT),
                    dateformat.time_format(self.end_hour, self.TIME_FORMAT))
            elif hour and self.start_hour:
                content += " (%s)" % dateformat.time_format(self.start_hour, self.TIME_FORMAT)
        return content

class Contact(models.Model):
    first_name = models.CharField("Prénom", max_length=50)
    last_name = models.CharField("Nom", max_length=50)
    email = models.EmailField("Courriel", max_length=100)

    def __str__(self):
        return " ".join([self.first_name, self.last_name])

main/forms.py
import re

from django import forms
from django.conf import settings
from django.contrib.contenttypes.forms import generic_inlineformset_factory

from captcha.fields import CaptchaField
from django_summernote.widgets import SummernoteWidget

from .models import Attachment, Contact, Page

YOUTUBE_IFRAME = r'''
    <iframe id="player" type="text/html" width="640" height="360"
    src="http://www.youtube.com/embed/\1?enablejsapi=1&origin=http://%s"
    frameborder="0"></iframe>''' % settings.ALLOWED_HOSTS[0]


class PageForm(forms.ModelForm):
    class Meta:
        model = Page
        fields = ['title', 'menu_title', 'content']
        widgets = {
            'content': SummernoteWidget(),
        }

    def __init__(self, *args, data=None, files=None, **kwargs):
        super().__init__(*args, data=data, files=files, **kwargs)
        AttachmentFormSet = generic_inlineformset_factory(model=Attachment, extra=1)
        self.formset = AttachmentFormSet(instance=self.instance, data=data, files=files)

    def clean_content(self):
        content = self.cleaned_data['content']
        content = re.sub(r'https://www\.youtube\.com/watch\?v=([_\w]*)', YOUTUBE_IFRAME, content)
        return content

    def is_valid(self):
        return all([super().is_valid(), self.formset.is_valid()])

    def save(self, **kwargs):
        instance = super().save(**kwargs)
        self.formset.save(**kwargs)
        return instance


class ContactForm(forms.Form):
    name = forms.CharField(max_length=200, label="Nom et prénom")
    email = forms.EmailField(label="Courriel")
    country = forms.CharField(max_length=100, label="Pays")
    message = forms.CharField(max_length=2000, label="Votre message", widget=forms.Textarea)
    target = forms.ModelChoiceField(label="Je désire contacter", queryset=Contact.objects.all())
    captcha = CaptchaField(help_text="Écrivez les lettres que vous voyez dans l'image")

main/views.py
from datetime import datetime

from django.conf import settings
from django.contrib import messages
from django.core.mail import send_mail
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.urls import reverse
from django.views.generic import FormView, TemplateView, UpdateView

from gallery.models import Gallery
from .forms import ContactForm, PageForm
from .models import Event, Page


class HomeView(TemplateView):
    template_name = 'index.html'

    def get_context_data(self, **context):
        context = super().get_context_data(**context)
        context['next_event'] = Event.published.order_by('start_date').first()
        return context


class PageMixin:
    def get_context_data(self, **context):
        context = super().get_context_data(**context)
        page = get_object_or_404(Page, slug=self.kwargs['slug'])
        context.update({
            'title': page.title,
            'page': page,
            'next_event': Event.published.order_by('start_date').first(),
            'can_edit': self.request.user.is_authenticated,
            'attachments': page.attachments.filter(visible=True),
        })
        if page.slug == settings.LIST_PASSED_EVENTS_ON:
            context['passed_events'] = Event.passed.order_by('-start_date')
        return context


class PageView(PageMixin, TemplateView):
    template_name = 'page.html'


class PageEditView(UpdateView):
    template_name = 'page_edit.html'
    model = Page
    form_class = PageForm


class GalleryListView(TemplateView):
    template_name = 'page_galleries.html'

    def get_context_data(self, **context):
        context = super().get_context_data(**context)
        page = get_object_or_404(Page, slug='galerie')
        context.update({
            'page': get_object_or_404(Page, slug='galerie'),
            'main_page': page,
            'galleries': Gallery.objects.filter(published=True),
        })
        return context


class GalleryDetailView(TemplateView):
    template_name = 'page_gallery.html'

    def get_context_data(self, **context):
        context = super().get_context_data(**context)
        page = get_object_or_404(Page, slug='galerie')
        context.update({
            'page': page,
            'main_page': page,
            'gallery': get_object_or_404(Gallery.objects.prefetch_related('photos'),
                                         slug=self.kwargs['slug']),
        })
        return context


class AgendaView(PageMixin, TemplateView):
    template_name = 'page_agenda.html'

    def get_context_data(self, **context):
        context = super().get_context_data(**context)
        context.update({
            'events': Event.published.order_by('start_date', 'start_hour'),
        })
        return context


class EventView(TemplateView):
    template_name = 'page_event.html'

    def get_context_data(self, **context):
        context = super().get_context_data(**context)
        context.update({
            'item': get_object_or_404(Event, pk=self.kwargs['target']),
        })
        return context


class ContactView(PageMixin, FormView):
    template_name = 'page_contact.html'
    form_class = ContactForm

    def form_valid(self, form):
        body = '''Envoyé le %(date)s
Envoyé par : %(name)s, %(email)s
Pays : %(country)s
Message :
%(message)s
''' % {
            'date': datetime.now(),
            'name': form.cleaned_data['name'],
            'email': form.cleaned_data['email'],
            'country': form.cleaned_data['country'],
            'message': form.cleaned_data['message'],
        }
        send_mail(
            "[cts-pro.org] Message du formulaire contact",
            body,
            settings.SERVER_EMAIL,
            settings.CONTACT_FORM_RECIPIENTS,
        )
        messages.success(self.request, "Merci pour l'envoi de votre message !")
        return HttpResponseRedirect(reverse('home'))

main/templates/base.html
{% load static mptt_tags %}
<DOCTYPE html>
<html>
<head>
  <meta name="description" content="Réseau d'activités dans les villages du Pied du Jura (villages de Apples, Ballens, Berolle, Bière, Bussy-Chardonney, Essertine-sur-Rolle, Gimel, Longirod, Marchissy, St- George, le Vaud, St-Oyens, Saubraz, Sévery, Pampigny, Mauraz, Montricher, L'Isle, Cossonay, Reverolle, Colombier, Vullierens, Mollens, Cuarnens, La Chaux, Mont la Ville, Senarclens, Grancy)">
  <title>{% block title %}{{ title }} | pieddujura.ch{% endblock %}</title>
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}"/>
  {% block extra_head %}{% endblock %}
</head>

<body>
<div id="container">

  <div id="head-top">
    <strong>pied du jura.ch</strong>
  </div>

  {% block banner %}{% endblock %}
  <div id="menubar">
    <ul id="menu-top">
    {% recursetree pages %}
        <li {% if not node.is_leaf_node %}class="menuparent"{% endif %}>
            {% if node.parent %}<a href="{{ node.get_absolute_url }}">{% endif %}{{ node.get_menu_title }}{% if node.parent %}</a>{% endif %}
            {% if not node.is_leaf_node or node.slug == 'galerie' %}
                <ul class="children">
                    {% if node.slug == 'galerie' %}
                        {% for gal in galleries %}
                        <li><a href="{% url 'gallery' gal.slug %}">{{ gal.title }}</a></li>
                        {% endfor %}
                    {% endif %}
                    {{ children }}
                </ul>
            {% endif %}
        </li>
    {% endrecursetree %}
    </ul>
  </div>

  {% if messages %}
    <ul class="messagelist">
        {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
  {% endif %}
  {% block content %}{% endblock %}

  <div id="footer">
  {% block footer %}{% endblock %}
  </div>

</div>
</body>
</html>

main/templates/index.html
{% extends "base.html" %}

{% block title %}Bienvenue sur le site «Au pied du Jura»{% endblock %}

{% block content %}
  <div id="main-home">
    <div id="background">&nbsp;</div>
    <div>&nbsp;</div>
    <div id="prochain" style="margin: 3em 2em 1em 4em;">
      {% if next_event %}
      <span class="home_title">Prochain événement:</span>
      {{ next_event.start_date|date:"j.m.Y" }} <a href="{{ next_event.get_absolute_url }}">{{ next_event.title }}</a>
      {% endif %}
    </div>

    <div class="banner_text" style="margin: 11em 2em 25em 4em;">
        <p style="font-size: 4em;">Au pied du Jura...</p>
        <p style="margin-left: 4em; margin-top: 4em; font-size: 1.8em;">... un réseau d'activités au pied du Jura vaudois.</p>
    </div>
    &nbsp;
  </div>
{% endblock %}

main/templates/login.html
{% extends "base.html" %}

{% block extra_head %}
<style>
form#login-form { width: 25em; margin: 0 auto; margin-top: 4em; }
form#login-form input { width: 100%; padding: 8px; }
</style>
{% endblock %}

{% block content %}
{% if user.is_authenticated %}
  <p>Vous êtes déjà connecté en tant que {{ user.username }}.</p>
{% else %}
<div id="content-main">
<form action="{{ app_path }}" method="post" id="login-form">{% csrf_token %}
  <div class="form-row">
    {{ form.username.errors }}
    {{ form.username.label_tag }} {{ form.username }}
  </div>
  <div class="form-row">
    {{ form.password.errors }}
    {{ form.password.label_tag }} {{ form.password }}
    <input type="hidden" name="next" value="{{ next }}" />
  </div>
  <div class="submit-row">
    <label>&nbsp;</label><input type="submit" value="Se connecter" />
  </div>
</form>

<script type="text/javascript">
document.getElementById('id_username').focus()
</script>
</div>
{% endif %}
{% endblock %}

main/templates/page.html
{% extends "base.html" %}
{% load static disp_utils mptt_tags %}

{% block banner %}
<div id="banner">
  <div>&nbsp;</div>
  <div class="banner_text banner_text_subpages">
    <p style="font-size: 2.5em; margin-top: 0; margin-bottom: 0.3em;">Au pied du Jura...</p>
    <p style="margin: 0.5em 1em 4em 6em; font-size: 1.2em;">... un réseau d'activités au pied du Jura vaudois.</p>
  </div>
  <div><br></div>
</div>
{% endblock %}


{% block content %}
<div id="leftbar">
    <ul id="menu-left">
    {% recursetree pages %}
        <li {% if not node.is_leaf_node %}class="menuparent"{% endif %}>
            {% if node.parent %}<a href="{{ node.get_absolute_url }}">{% endif %}{{ node.get_menu_title }}{% if node.parent %}</a>{% endif %}
            {% if node.level < 1 %}
                <ul class="children">
                    {% if node.slug == 'galerie' %}
                        {% for gal in galleries %}
                        <li><a href="{% url 'gallery' gal.slug %}">{{ gal.title }}</a></li>
                        {% endfor %}
                    {% endif %}
                    {{ children }}
                </ul>
            {% endif %}
        </li>
    {% endrecursetree %}
    </ul>
</div>

<div id="content">
    {% if can_edit %}<div class="edit_btn"></div>{% endif %}
    <h2>{{ title }}</h2>
    
    <div class="page-content">
      {% block pagecontent %}{% show_content page %}{% endblock %}
      {% for event in passed_events %}
      <div class="event-summary">
          <a href="{{ event.get_absolute_url }}">{{ event.date_long }}</a> {{ event }}
      </div>
      {% endfor %}
    </div>
</div>
{% endblock %}

{% block footer %}
    {{ block.super }}
    {% if user.is_authenticated %}
    <div class="edit-icons"><a href="{% url 'page_edit' page.slug %}">&#x270D;</a></div>
    {% endif %}
{% endblock %}

main/templates/page_agenda.html
{% extends "page.html" %}
{% load static disp_utils %}

{% block pagecontent %}
    <table class="agenda">
    {% for item in events %}
        <tr class="item"><td class="date"><a name="item{{ item.pk }}"></a>{{ item|event_date }}</td>
                         <td class="title">{{ item.title }}</td></tr>
        {% if item.description %}<tr><td colspan="2" class="description">{{ item.description|safe }}</tr>{% endif %}
    {% empty %}
        <tr><td><p><i>Aucun événement planifié pour l'instant.</i></p></td></tr>
    {% endfor %}
    </table>
{% endblock %}

{% block footer %}
    {% if user.is_authenticated %}
    <div class="edit-icons">
        <a href="{% url 'page_edit' page.slug %}">&#x270D;</a> (page)<br>
        <a href="{% url 'admin:main_event_changelist' %}">&#x270D;</a> (agenda)
    </div>
    {% endif %}
{% endblock %}

main/templates/page_contact.html
{% extends "page.html" %}

{% block extra_head %}
<style>
form#contact th { text-align: right; vertical-align: top; padding: 8px; }
form#contact input[type=text],
form#contact input[type=email],
form#contact textarea { width: 100%; }
</style>
{% endblock %}

{% block pagecontent %}
<form id="contact" method="post">
<table>
    {{ form.as_table }}
</table>
<input type="submit" value="Envoyer">
</form>
{% endblock %}

main/templates/page_edit.html
{% extends "base.html" %}

{% block title %}{{ page.title }}{% endblock %}

{% block extra_head %}
  <style>
    input[type=text], textarea { width: 100%; }  
    input#id_title { font-size: 115%; font-weight: bold; }
    textarea#id_content { width: 100%; }
    div.page_content { margin: 1em 0; }
    div.buttons { margin-top: 1em; }
  </style>
  {{ form.media }}
{% endblock %}

{% block content %}
    <form enctype="multipart/form-data" method="post" action=".">{% csrf_token %}
    <div class="page_container">
        <h1>{{ form.title }}</h1>
        <div>Titre dans le menu :<br>{{ form.menu_title }}</div>
        <div class="page_content">
            {{ form.content }}
        </div>
        <div class="formset">
            {{ form.formset.management_form }}
            {% for subform in form.formset %}
                <fieldset><div class="formsetEntry">{{ subform.as_p }}</div></fieldset>
            {% endfor %}
        </div>
    </div>
    <div class="buttons">
        <div style="float:right;"><input type="submit" value="Enregistrer"></div>
        <input type="button" value="Annuler" onclick="window.location.href={% url 'page' page.slug %};">
    </div>
    </form>
{% endblock %}

{% block footer %}

{% endblock %}

main/templates/page_event.html
{% extends "page.html" %}
{% load static disp_utils %}

{% block pagecontent %}
    <table class="agenda">
        <tr class="item"><td class="date"><a name="item{{ item.pk }}"></a>{{ item|event_date }}</td>
                         <td class="title">{{ item.title }}</td></tr>
        {% if item.description %}<tr><td colspan="2" class="description">{{ item.description|safe }}</tr>{% endif %}
    </table>
{% endblock %}

{% block footer %}
    {% if user.is_authenticated %}
    <div class="edit-icons">
        <a href="{% url 'admin:main_event_change' item.pk %}">&#x270D;</a>
    </div>
    {% endif %}
{% endblock %}

main/templates/page_galleries.html
{% extends "page.html" %}
{% load thumbnail %}

{% block extra_head %}{{ block.super }}
<style>
  div.gallery {display: inline-block; width: 33%; text-align: center; vertical-align: top; padding: 1em;}
  div.gallery img { width: 140px; }
</style>
{% endblock %}

{% block page_content %}
    {{ page.content|safe }}
    <div>
        {% for gal in galleries %}
        <div class="gallery">
            <a href="{% url 'gallery' gal.slug %}">
              <img src="{{ gal.photos.first.image|thumbnail_url:'thumbnail' }}"><br>
              {{ gal.title }}
            </a>
        </div>
        {% endfor %}
    </div>
{% endblock %}

{% block footer %}
    {% if user.is_authenticated %}
    <div class="edit-icons">
        <a href="{% url 'page_edit' page.slug %}">&#x270D;</a> (page)<br>
        <a href="{% url 'admin:gallery_gallery_changelist' %}">&#x270D;</a> (galeries)
    </div>
    {% endif %}
{% endblock %}

main/templates/page_gallery.html
{% extends "page.html" %}
{% load thumbnail %}{% load static from staticfiles %}

{% block extra_head %}{{ block.super }}
<script src="//code.jquery.com/jquery-3.3.1.min.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.4.1/jquery.fancybox.min.css">
<script src="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.4.1/jquery.fancybox.min.js"></script>
<style>
  div.photo {display: inline-block; width: 15%; text-align: center; padding: 1em;}
  div.photo img {width: 100px;}
</style>
{% endblock %}

{% block pagecontent %}
    <h2>{{ gallery.title }}</h2>
    {% if gallery.description %}<p>{{ gallery.description }}</p>{% endif %}
    <div>
        {% for photo in gallery.photos.all %}
        <div class="photo">
            <a class="photo" data-fancybox="gallery" href="{{ photo.image|thumbnail_url:'gallery' }}">
              <img src="{{ photo.image|thumbnail_url:'thumbnail' }}"><br>
              {{ photo.title }}
            </a>
        </div>
        {% empty %}<p><i>Cette galerie ne contient aucune photo pour l'instant.</i></p>
        {% endfor %}
    </div>
{% endblock %}

{% block footer %}
    {% if user.is_authenticated %}
    <div class="edit-icons">
        <a href="{% url 'admin:gallery_gallery_change' gallery.pk %}">&#x270D;</a> (galerie)
    </div>
    {% endif %}
{% endblock %}